#!/usr/bin/env bash

export BASH_SILENCE_DEPRECATION_WARNING=1

if command -v brew &> /dev/null; then
    COMPL_SCRIPT="$(brew --prefix)/etc/profile.d/bash_completion.sh"
    if [ -f "$COMPL_SCRIPT" ]; then
        . "$COMPL_SCRIPT"
    fi
fi

ANDROID_HOME=/Users/$USER/Library/Android/sdk/

export ANDROID_HOME

