#!/usr/bin/env bash

export BASH_SILENCE_DEPRECATION_WARNING=1

if command -v brew &> /dev/null; then
    COMPL_SCRIPT="$(brew --prefix)/etc/bash_completion"
    if [ -f "$COMPL_SCRIPT" ]; then
        . "$COMPL_SCRIPT"
    fi
fi
