#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd & echo "sxhkd PID = $!"
# pgrep -x panel.sh > /dev/null || panel.sh & echo "panel PID = $!"
# pgrep -x panel > /dev/null || panel & echo "panel PID = $!"

# Located in ~/.local/bin/launch_polybar.bash. Available in path.
launch_polybar.bash
# launch_panel.bash
# polybar &

# Set wallpaper
BG="$HOME/Pictures/bg.png"
if [ -f "$BG" ]; then
	xwallpaper --center "$BG"
fi

# Use only connected and active (active is detected through the resolution)
monitors=$(xrandr --query | grep "connected" | grep '[0-9]\+x[0-9]\++[0-9]\++[0-9\+]')
if [ $(echo "$monitors" | wc -l) -gt 1 ]; then
	if echo $monitors | grep -q eDP; then
		bspc monitor eDP -d 1 2 3 4 5 6 7 8 9
		bspc monitor HDMI-A-0 -d 10
		bspc wm -O eDP HDMI-A-0
	elif echo $monitors | grep -q "DisplayPort-1"; then
		bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
		bspc monitor DisplayPort-1 -d 10
		bspc wm -O HDMI-A-0 DisplayPort-1
	fi
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_monitor true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
