#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd & echo "sxhkd PID = $!"
# pgrep -x panel.sh > /dev/null || panel.sh & echo "panel PID = $!"
# pgrep -x panel > /dev/null || panel & echo "panel PID = $!"

# Located in ~/.local/bin/launch_polybar.bash. Available in path.
# launch_polybar.bash
panel.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
